backend:
  name: git-gateway
  branch: main

# Se o erro persistir, o CMS tentará usar o Identity diretamente
publish_mode: simple

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "settings"
    label: "Configurações"
    files:
      - name: "contacts"
        label: "Contactos"
        file: "data/settings.json"
        fields:
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Morada", name: "address", widget: "text"}
          - {label: "Facebook", name: "facebook", widget: "string"}

  - name: "blog"
    label: "Blog"
    folder: "data/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
